### ISSUE TITLE
The /bridge/ endpoints work but the /api/ ones do not

### ISSUE THREAD

**Issue by pyrocumulus** [TrafeX/nefiteasy-http-server-docker#1]
At first I thought this was an issue in the `nefit-easy-http-server` itself, but recently I found out that that package is working fine locally. It's just the docker image that does not seem to support the `/api/` endpoint. See also [this issue](https://github.com/robertklep/nefit-easy-http-server/issues/8) on the Nefit easy http server package. I'm not very good with Docker (and especially node), so I haven't build my own Docker file yet to try and figure this thing out.

However I see now that you do not list the `/api/` endpoints in your Readme either. Is that by accident or do you really not support them? I can't see any particular reason why that would be, because as far as I know it's built-in in the package itself; so I still don't understand how the `/bridge/` could work while the `/api/' doesn't.

Curious as to what you think on this :) I would really like to be able to query the `/api/` endpoints in my own projects, preferably via a Docker container.

**Comment by TrafeX** [comment]
Hi,

The problem was that this Docker container was still using the 2.x version of https://github.com/robertklep/nefit-easy-http-server and that version doesn't have the `/api/` endpoint.
I just updated to 3.1.x which includes the `/api` endpoint as mentioned here; https://github.com/robertklep/nefit-easy-http-server#commands-api

Please try the latest tag of this container and let me know if this solves your problem!

**Comment by pyrocumulus** [comment]
Thanks! If I have the time, I'll update my container tonight and check the results. I'll let you know 👍

**Comment by pyrocumulus** [comment]
Works like a charm. Api now returns information just like the bridge endpoint. Thanks!
